language: node_js
node_js: node
script:
  - yarn test
  - yarn build

env:
  - API_URI=https://seabrook-api.cfapps.io

cache:
  directories:
    - elm-stuff
    - tests/elm-stuff
    - sysconfcpus
    - node_modules

# build time improvement see: https://git.io/vQcqz
before_install:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

# build time improvement see: https://git.io/fNoua
install:
  - yarn install
  - echo "Preparing compilation..."
  - '[ -e "$(yarn bin)/webpack-old" ] || mv $(yarn bin)/webpack $(yarn bin)/webpack-old'
  - printf "#\041/bin/bash\n\necho \"Running webpack with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 webpack-old \"\$@\"" > $(yarn bin)/webpack
  - chmod +x $(yarn bin)/webpack
  - travis_retry elm package install --yes
  - echo "Preparing tests..."
  - '[ -e "$(yarn bin)/elm-make-old" ] || mv $(yarn bin)/elm-make $(yarn bin)/elm-make-old'
  - printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(yarn bin)/elm-make
  - chmod +x $(yarn bin)/elm-make
  - pushd tests
  - PATH=$PATH:../node_modules/.bin travis_retry elm package install --yes
  - popd


deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: alidaka@pivotal.io
  password:
    secure: mLhSdxlwB/5mRrOi3N5IQprNDzl0F0SvM3rhEuYCmuWDoZmIiWl+xnfYabiO5hhKXcUC1KNthPkpAenPgsewV7L38Q795wNHIM8QvA03I0jo7ZQ+3DBKaxMpdp4hFOWwoi/ZnlOak358jHO043GeILnp/+txGazCVts2KUJc4Ft/syBPkx7TOiRMTGYtks8LB+cX6HFnmRD9Jh7byPpTYHwBoaAp6MJyTQ7HbfJDaeX19+saKVBkq3ONgEBKqSBdez9ShfKuf4CaHVu9aB2jNzz9NGSL+i11HG/aWJdeWzaNivb6E2Wk8bVS7ChOtJIHTvnm5vkFu9UqdHvi11wqADNKuE/GzKuvi2xi7iB1yPNuQfDwYD4VpjefkkNeoTzls2GX+uVP09U7biIzpY/IFKlD4XrSg8NgjmhBSpfmQhiuIeaT5HKG0L12hmHY/+FWQwpQ2tipIKDyPcFjZr8jdJrQtowMrdILKK7lK/Z1MJ3MtHQTBblsb/zxutciVjW57vCGBZZ7DFPmcd5IjzLz5Td84a+9GBieokDBiBPOwGJ31u7AIX4jbyNMM7FenL9GcUEhDLCbWzt64GSWmb5XUtNoqjWtCK+90/mhCJTHj0dWJpJTvLqpkUAvlzE2GVKVGyBreL8ntinno+L4S5Kw8+Wlxxd+dUvuxWq53A3iHIA=
  organization: seattle-beach
  space: book-club
  on:
    repo: seattle-beach/seabrook-web
    branch: master
